import { expect, test } from '@playwright/test';
import { writeFile } from 'node:fs/promises';
import { createDriver, readGame, waitFact, waitReady, type GameRead } from './driver';

const allFacts = ['PACKAGE_RECEIVED', 'CITY_ENTERED', 'TREE_DISCOVERED', 'INNER_WORLD_ENTERED', 'MONEY_REFLECTION_SAVED', 'MARKET_VISITED', 'ATTACHMENT_TRIGGERED', 'ATTACHMENT_SEEN'];
const steps = ['lock', 'fade-out', 'save', 'prepare', 'switch', 'state', 'fade-in', 'unlock'];
const response = '<b>Money means room to rest.</b> & time with family.';

for (const placeholder of [false, true]) {
  test(`full slice with ${placeholder ? 'placeholder' : 'normal'} assets`, async ({ page }, testInfo) => {
    test.setTimeout(360000);
    const errors: string[] = [];
    const posts: string[] = [];
    page.on('pageerror', error => errors.push(error.message));
    page.on('console', message => { if (message.type() === 'error') errors.push(message.text()); });
    page.on('request', request => { if (request.method() === 'POST') posts.push(request.url()); });
    const url = `/?test${placeholder ? '&assets=placeholder' : ''}`;
    await page.goto(url);
    await waitReady(page);
    const zones: { name: string; world: string; position: GameRead['position']; stats: GameRead['stats'] }[] = [];
    const sample = async (name: string) => {
      const snapshot = await readGame(page);
      zones.push({ name, world: snapshot.world, position: snapshot.position, stats: snapshot.stats });
    };
    await sample('arrival');
    if (!placeholder) {
      const groups = (await readGame(page)).animation.groups.map(group => group.name);
      expect(groups.some(name => /idle/i.test(name))).toBe(true);
      expect(groups.some(name => /walk/i.test(name))).toBe(true);
    }
    const mobile = testInfo.project.name === 'mobile';
    let driver = await createDriver(page, mobile);
    try {
      await driver.moveTo(1.2, -45, 0.4);
      await expect(page.locator('.lw-prompt')).toContainText('Receive package');
      await driver.act();
      await waitFact(page, 'PACKAGE_RECEIVED');
      await driver.moveTo(0, -23);
      await waitFact(page, 'CITY_ENTERED');
      await sample('city');
      await driver.moveTo(0, -3.8, 0.35);
      await waitFact(page, 'TREE_DISCOVERED');
      await sample('outer-tree');
      await expect(page.locator('.lw-prompt')).toContainText('Hold to look within');
      await driver.act(1500);
      await waitFact(page, 'INNER_WORLD_ENTERED');
      expect((await readGame(page)).world).toBe('inner');
      expect((await readGame(page)).transitions.map(log => log.step)).toEqual(steps);
      await driver.moveTo(4, -3, 0.45);
      await sample('inner-package');
      await expect(page.getByRole('dialog')).toBeHidden();
      await expect(page.locator('.lw-prompt')).toContainText('Reflect');
      await driver.act();
      const field = page.getByRole('dialog').getByRole('textbox');
      await expect(field).toBeFocused();
      await field.fill(response);
      await expect(field).toHaveValue(response);
      expect(await page.getByRole('dialog').locator('b,img,script').count()).toBe(0);
      if (mobile) await page.getByRole('button', { name: 'Save', exact: true }).tap();
      else await page.getByRole('button', { name: 'Save', exact: true }).click();
      await waitFact(page, 'MONEY_REFLECTION_SAVED');
      expect((await readGame(page)).state.reflections.money).toBe(response);
      await page.waitForTimeout(1200);
      const beforeReload = await readGame(page);
      await driver.dispose();
      await page.reload();
      await waitReady(page);
      const resumed = await readGame(page);
      expect(resumed.world).toBe('inner');
      expect(resumed.state.reflections.money).toBe(response);
      expect(Math.hypot(resumed.position.x - beforeReload.position.x, resumed.position.z - beforeReload.position.z)).toBeLessThan(0.25);
      driver = await createDriver(page, mobile);
      await driver.moveTo(0, -3.8, 0.25);
      await expect(page.locator('.lw-prompt')).toContainText('Hold to return');
      await driver.act(1500);
      await waitReady(page);
      expect((await readGame(page)).world).toBe('outer');
      await driver.moveTo(8, -6);
      await driver.moveTo(19, -5);
      await driver.moveTo(25, -1.5, 0.4);
      await waitFact(page, 'MARKET_VISITED');
      await sample('market');
      await expect(page.locator('.lw-prompt')).toContainText('Look at the shining object');
      await driver.act();
      await waitFact(page, 'ATTACHMENT_TRIGGERED');
      await expect.poll(async () => (await readGame(page)).wavesShown).toHaveLength(1);
      await driver.act();
      expect((await readGame(page)).wavesShown).toHaveLength(1);
      await driver.moveTo(19, -5);
      await driver.moveTo(8, -6);
      await driver.moveTo(0, -3.8, 0.35);
      await driver.act(1500);
      await waitFact(page, 'ATTACHMENT_SEEN');
      await driver.moveTo(5.5, -2.4, 0.45);
      const final = await readGame(page);
      await sample('attached-beetle');
      console.log(JSON.stringify({ project: testInfo.project.name, assets: placeholder ? 'placeholder' : 'normal', stats: final.stats, facts: final.state.facts.length, wavesShown: final.wavesShown.length, beetle: final.beetle }));
      expect(final.world).toBe('inner');
      expect(final.beetle).toBe(true);
      expect(final.state.facts.sort()).toEqual([...allFacts].sort());
      expect(final.state.traits.attachment).toBeCloseTo(0.45);
      expect(final.wavesShown).toHaveLength(1);
      expect(final.state.waveIds).toEqual(['attachment-desire']);
      expect(final.transitions).toHaveLength(16);
      expect(final.transitions.slice(0, 8).map(log => log.step)).toEqual(steps);
      expect(final.transitions.slice(8, 16).map(log => log.step)).toEqual(steps);
      expect(final.transitions[15].time - final.transitions[8].time).toBeLessThanOrEqual(2000);
      await expect(page.locator('.lw-hint')).toContainText('You have met the beetle');
      await page.screenshot({ path: testInfo.outputPath('attached-beetle.png') });
      const statePath = testInfo.outputPath('final-read.json');
      const zonesPath = testInfo.outputPath('zone-stats.json');
      await writeFile(statePath, JSON.stringify(final, null, 2));
      await writeFile(zonesPath, JSON.stringify(zones, null, 2));
      await testInfo.attach('final-read.json', { path: statePath, contentType: 'application/json' });
      await testInfo.attach('zone-stats.json', { path: zonesPath, contentType: 'application/json' });
      console.log(JSON.stringify({ project: testInfo.project.name, assets: placeholder ? 'placeholder' : 'normal', zones }));
      await driver.dispose();
      await page.reload();
      await waitReady(page);
      const reloaded = await readGame(page);
      expect(reloaded.world).toBe('inner');
      expect(reloaded.beetle).toBe(true);
      expect(reloaded.state.facts.sort()).toEqual([...allFacts].sort());
      expect(reloaded.state.reflections.money).toBe(response);
      expect(reloaded.wavesShown).toEqual([]);
      expect(reloaded.waves).toBe(0);
      expect(reloaded.state.waveIds).toEqual(['attachment-desire']);
      expect(errors).toEqual([]);
      expect(posts).toEqual([]);
    } finally { await driver.dispose().catch(() => {}); }
  });
}
