import { test } from '@playwright/test';
import { writeFile } from 'node:fs/promises';
import { createDriver, readGame, waitFact, waitReady } from './driver';
const tag = process.env.SHOT_TAG ?? 'after';
const extra = process.env.SHOT_Q ?? '';
const only = process.env.SHOT_ONLY ?? '';
test('shots', async ({ page }, info) => {
  test.setTimeout(400000);
  const prefix = info.project.name === 'mobile' ? 'phone' : 'desktop';
  const dir = 'docs/evidence/wp-42/';
  const out: Record<string, unknown> = {};
  const errors: string[] = [];
  page.on('pageerror', e => errors.push(e.message));
  page.on('console', m => { if (m.type() === 'error') errors.push(m.text()); });
  await page.goto('/?test&debug' + extra);
  await waitReady(page);
  const shot = async (name: string) => {
    await page.waitForTimeout(900);
    const r = await readGame(page);
    out[name] = { stats: r.stats, cam: r.camera, pos: r.position };
    await page.screenshot({ path: `${dir}${prefix}-${name}-${tag}.png` });
  };
  const mobile = info.project.name === 'mobile';
  const driver = await createDriver(page, mobile);
  await shot('spawn');
  await driver.moveTo(1.2, -45, 0.4); await driver.act(); await waitFact(page, 'PACKAGE_RECEIVED');
  await driver.moveTo(0, -23); await waitFact(page, 'CITY_ENTERED'); await shot('gate');
  await driver.moveTo(0, -3.8, 0.35); await waitFact(page, 'TREE_DISCOVERED'); await shot('square');
  await driver.act(1500); await waitFact(page, 'INNER_WORLD_ENTERED');
  await driver.moveTo(4, -3, 0.45); await shot('inner-package');
  await driver.act(); await page.getByRole('dialog').getByRole('textbox').fill('Rest.');
  if (mobile) await page.getByRole('button', { name: 'Save', exact: true }).tap(); else await page.getByRole('button', { name: 'Save', exact: true }).click();
  await waitFact(page, 'MONEY_REFLECTION_SAVED');
  await driver.moveTo(0, -3.8, 0.25); await driver.act(1500); await waitReady(page);
  await driver.moveTo(8, -6); await driver.moveTo(19, -5); await driver.moveTo(25, -1.5, 0.4); await waitFact(page, 'MARKET_VISITED'); await shot('market');
  await driver.act(); await waitFact(page, 'ATTACHMENT_TRIGGERED'); await page.waitForTimeout(2500);
  await driver.moveTo(19, -5); await driver.moveTo(8, -6); await driver.moveTo(0, -3.8, 0.35); await driver.act(1500); await waitFact(page, 'ATTACHMENT_SEEN');
  await driver.moveTo(5.5, -2.4, 0.45); await shot('beetle');
  await writeFile(`${dir}measure-${prefix}-${tag}.json`, JSON.stringify({ out, errors }, null, 1));
  await driver.dispose();
});
