export const strings = {
  title:'Light Within', outer:'The City', inner:'Within',
  receive:'Receive package', look:'Hold to look within', reflect:'Reflect',
  return:'Hold to return', desire:'Look at the shining object',
  question:'What does money mean to you?', wave:'I want more...',
  end:'You have seen the attachment beetle. This is the end of this first part.',
  welcome:'Follow the path. Take the package at the stone.',
  carrying:'The gate is open. Follow the path to the tree.',
  reflectionHelp:'Your words stay on this device. There is no right answer.',
  save:'Save', skip:'Skip', pause:'Pause', resume:'Resume', newGame:'New Game',
  delete:'Delete reflections', confirmNew:'Start a new game? This removes this saved game.',
  confirmDelete:'Delete your saved words? Your game progress stays.',
  controls:'W A S D: move · Shift: run · E: act or hold · Drag: look · Esc: pause',
  loading:'Loading the world...', bootError:'The world could not start. Reload to try again.',
  act:'Act', run:'Run', cancel:'Cancel', confirm:'Confirm', words:'Your words',
  touchMove:'Move', touchLook:'Drag the view to look', reflectionCount:'characters',
  nextMarket:'Return to the city. Visit the market to the right of the tree.',
  nextInner:'Return to the tree. Look within once more.',
  treeHelp:'Hold E at the light by the tree.',
  innerHelp:'Go to the package by the root. Press Reflect.',
  savedHelp:'Your words are saved. Hold at the light by the trunk to return.',
  skippedHelp:'You can return at the light by the trunk.',
  quality:'View detail', simple:'Simple', full:'Full',
  storageNotice:'This device cannot save your game. Keep this tab open.',
  actionKey:'E',
};
