import {readFile,writeFile,mkdir} from 'node:fs/promises';
const source=await readFile('bitte-lies-dir-folgendes-eager-sutton.md','utf8');
const adjusted=source.replace(/## Model guide[\s\S]*?(?=## Work packages)/,`## ChatGPT-only model guide\n- The lead and all helpers use the ChatGPT model of this Codex session.\n- No Claude credits or Claude service are needed.\n- Lead owns contracts, integration, review and browser checks.\n- Helpers own state/save/rules; input/UI/waves; assets/worlds/props.\n- Each helper has a separate branch and worktree. No helper changes shared contracts.\n- Model changes need available tool support. Do not pretend to run an unavailable model.\n- User instruction on 2026-10-01 authorizes continuing beyond WP-00 through v0.1.\n- D1 and D2 real-phone checks remain user checks. Continue desktop work while they are open.\n\n`).replace(/Claude Code \+ Codex/g,'ChatGPT Codex').replace(/One Lead \(Opus\)/g,'One ChatGPT lead').replace(/\*\*Opus\*\* \(Astra\)|\*\*GPT-6 Astra\*\* \(Opus\)|\*\*5\.6 Sol\*\* \(Sonnet\)|Sonnet \(5\.6 Sol\)|Sonnet \+ Opus review|Sonnet → Opus if stuck|\*\*Opus\*\* \(\+ optional Astra review\)|\*\*GPT-6 Astra\*\*|\*\*5\.6 Sol\*\*|\*\*Opus\*\*|Haiku \(5\.6 Luna\)|Opus = me, after approval/g,'ChatGPT').replace(/STOP and report\. You start WP-01\. No game code is written in this step\./g,'Continue with WP-01 and the next waves under the current user instruction.');
await writeFile('docs/PLAN.md',`# Active execution plan\n\nThis copy replaces the old model assignments. All agents use ChatGPT.\nThe source plan stays unchanged for traceability.\n\n${adjusted}`);
const rows=[...source.matchAll(/^\| (\d\d[Rab]?|A[1-4]) \| ([^|]+) \| ([^|]+) \|.*$/gm)];
const records=[];
for(const row of rows){
 const [line,id,name,wave]=row;const parts=line.split('|').map(x=>x.trim());
 const record={id,name:name.trim(),wave:wave.trim(),needs:parts.length===9?parts[4]:'see plan',model:'ChatGPT session model',status:id==='00'?'done':'pending',acceptance:parts.at(-2)};
 records.push(record);
 await writeFile(`docs/wp/WP-${id}.md`,`# WP-${id}: ${record.name}\n\n- Model: ${record.model}.\n- Wave: ${record.wave}.\n- Read: AGENTS.md, GAME_MASTER_SPEC.md, docs/PLAN.md, docs/3D_ASSET_GENERATION_MASTER.md.\n- Needs: ${record.needs}.\n- Ownership: use the module map in docs/PLAN.md. Lead owns shared files.\n- Use the types in src/contracts. Report a needed change before changing them.\n- Scope: the slice ends at the attached beetle.\n- Done when: ${record.acceptance}.\n- Checks: npm run typecheck; npm run lint; npm test; npm run build. Add browser or asset checks where needed.\n- Hand-off: docs/reports/WP-${id}.md and docs/decisions/WP-${id}.md. State proof and open checks.\n`);
}
await writeFile('docs/work-packages.json',JSON.stringify({modelPolicy:'ChatGPT only',packages:records},null,2)+'\n');
const decisions=source.match(/## Architecture decisions[\s\S]*?(?=## Model guide)/)?.[0]??'';
await writeFile('DEVELOPMENT_DECISIONS.md',`# Development decisions\n\n${decisions}\n\n## Execution update, 2026-10-01\n- All work uses ChatGPT agents. The original model names are no longer task assignments.\n- Combine leaf packages into three owned worktrees to reduce merge cost. Preserve the package checks.\n- Root Git exists with an unborn main branch and a prefilled index. Keep user files. Exclude generated and unrelated temporary data from the first commit.\n- Google Drive sync state cannot be proved here. Do not change the user's sync app.\n- The older 8.x player proof is evidence only. Test the current 9.x runtime.\n- A3 rig work and final art may stay a separate track when the fallback clips meet the slice needs.\n- Real phone checks need the user device. Browser touch tests are separate evidence.\n`);
await writeFile('docs/reports/WP-00.md','# WP-00\n\n- Read both plans and both master documents.\n- Read all five concept sheets.\n- Set up Git excludes, work rules, shared types and task briefs.\n- Copy only the asset contract document from the other project. No outside code copied.\n- All tasks use ChatGPT.\n- Continue through the slice under the current user instruction.\n- Google Drive pause and real-phone checks remain unverified.\n');
await mkdir('docs/decisions',{recursive:true});
await writeFile('docs/decisions/WP-00.md','# WP-00\n\nSee the execution update in DEVELOPMENT_DECISIONS.md.\n');
